### ISSUE TITLE
Using ClouDNS-Go

### ISSUE THREAD

**Issue by wmarchesi123** [ppmathis/cloudns-go#2]
I am looking to import cloudns-go into a Golang project, though I am getting the error shown below:

I used `go get github.com/snapserv/cloudns-go` and received the following error:
```
go: github.com/snapserv/cloudns-go@v0.0.0-20191230224331-af7762f66d70: parsing go.mod:
        module declares its path as: cloudns-go
                but was required as: github.com/snapserv/cloudns-go
```

I am sure I am missing something simple to resolve the issue, but would love pointed in that direction.

**Comment by ppmathis** [comment]
@wmarchesi123 Thank you for your issue. Back when I've written this library I implemented most API endpoints and used them in a private project, but did not get to fully releasing it, so it's not really been that usable by others. I implemented a couple changes just now, mainly switching the license to MIT (more permissive), using GitHub Actions + Codecov for CI, relocating the repository to `ppmathis` (the previous namespace was never really appropriate either), fixing a few other small details and tagging it as `1.0.0`.

You should now be able to regularly use it by importing `github.com/ppmathis/cloudns-go` in your project. I also double-checked the implementation against the current API and everything still works except disabling a dynamic URL, as there is an undocumented change from ClouDNS. I will follow up with them and get that fixed too, but aside from that one feature you should be able to use everything.

Let me know if you face any other issues and I'm happy to take a look.

**Comment by wmarchesi123** [comment]
@ppmathis Thank you for the insanely fast response! Working on adding ClouDNS as a provider to the open-source Kubernetes-sigs project External-DNS. You can see my fork and branch here: [wmarchesi123/external-dns/cloudns](https://github.com/wmarchesi123/external-dns/tree/cloudns).

Looks like you may need to create a release in addition to the tag. I am now importing it fine but with version `go: added github.com/ppmathis/cloudns-go v0.0.0-20221221222800-2a276d83cfa3`.

**Comment by ppmathis** [comment]
@wmarchesi123 Good catch! I simply missed the v-prefix for the tag which Go requires for a package to be properly versioned, should be fixed now as well. I’ll release v1.0.1 in the next days with updated test fixtures and dependencies as well, then everything should be up-to-date again.

That’s a great project idea by the way, would even be something I could use in a Kubernetes cluster I’m operating. 👍

**Comment by wmarchesi123** [comment]
@ppmathis Feel free to contact me on the Kubernetes Slack or via my [email will@marchesi.io](mailto:will@marchesi.io). I think it would be a great chat.
